### PR TITLE
Update the Submission.submissionStatus of candidate Submissions from a Quartz job

### PR DESCRIPTION
**Pull request by emetsger**
Moves the logic out of the `DepositProcessor` to a dedicated Quartz job.

- Valid candidate Submissions are those with an existing 'submissionStatus' not equal to COMPLETE or CANCELLED
- Upgrade to version 5.0.2 (from 5.0.0) of the PassClient, which contains bug fixes to the SubmissionStatusService

Resolves https://github.com/OA-PASS/general-issues/issues/117

### CODE REVIEW

**Comment by karenhanson** [comment]
Question: In PASS right now there are ~920 submission with a status of `submitted` and ~280 with a status of `needs-attention`. Would this attempt to update the status of every one of those every time it runs? If so that may be too much - we may need to wait until we can put some date filters on ES queries...

**Comment by emetsger** [comment]
@karenhanson yes, all of those Submissions would be updated every time the job runs.

The quartz job runs every 10 minutes and the jobs cannot run concurrently.  So it will be OK if a job takes longer than 10 minutes to run.

If the concern is spamming Fedora with requests, I can build in a pause between each query to the submission status service.

We could wait, but unfortunately I think this needs to be addressed shortly.

**Comment by karenhanson** [comment]
My concern is the effect on performance. I'm not sure if running several thousand queries in quick succession every 10 minutes would have a noticeable impact or not. If it would, It might be worth moving forward with the change to add Fedora dates to Elasticsearch records (which I think needs to be done sooner or later) so that we could update based on recent updates on RepositoryCopy or Deposit records instead.

**Comment by emetsger** [comment]
@karenhanson well, there's enough logging now in the updater where we can measure the performance impact in terms of the time it takes to run the job.  So I'd say we can merge this (when the build succeeds) and evaluate in demo.

**Comment by karenhanson** [comment]
Sounds good! Perhaps we can switch things around when those dates are available.

**Comment by emetsger** [comment]
@karenhanson yeah a better approach may be to use the ES query dsl directly.  either way, dates will will help reduce the number of entities to scan.

**Comment by emetsger** [comment]
This PR uncovered an issue where the indexer was not properly communicating with Fedora, so there are a series of commits (labeled IT fixes) included in this PR which fix that.

**Pull request merged**
